name: Build docker image

on: [push, create]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --tag mrtalon63/packetcrypt:latest .

    - name: Login to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: mrtalon63
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to registry as version
      run: docker push mrtalon63/mrtalon63/packetcrypt:latest
