name: Build docker image

on: [push, create]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --tag mrtalon63/packetcrypt:dev .

    - uses: docker/login-action@v1.12.0
      with:
        username: mrtalon63
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to registry as version
      run: docker push mrtalon63/packetcrypt:latest
